// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/docs" | "/help" | "/instructor" | "/instructor/courses" | "/instructor/courses/add_member" | "/instructor/courses/create" | "/instructor/courses/drop_member" | "/instructor/courses/labs" | "/instructor/courses/roster" | "/instructor/create_user" | "/instructor/edit_lab/[uid]" | "/instructor/labs" | "/instructor/manage_roles" | "/instructor/user_search" | "/labs" | "/login" | "/new-project" | "/profile" | "/projects" | "/projects/[projectId]" | "/settings" | "/student" | "/student/docs" | "/student/help" | "/student/labs" | "/student/labs-root" | "/student/labs/[uid]" | "/student/new-project" | "/student/profile" | "/student/projects" | "/student/projects/[projectId]" | "/student/settings" | "/ta"
type AppRouteHandlerRoutes = "/api/add_course_lab" | "/api/add_course_member" | "/api/course_labs" | "/api/course_members" | "/api/create_course" | "/api/create_lab" | "/api/create_test_case" | "/api/delete_lab" | "/api/delete_test_case" | "/api/grade_lab" | "/api/grade_status" | "/api/lab_courses" | "/api/lab_submissions" | "/api/list_courses" | "/api/list_labs" | "/api/list_test_cases" | "/api/load_lab_session" | "/api/load_workspace" | "/api/remove_course_lab" | "/api/remove_course_member" | "/api/run" | "/api/score" | "/api/student_course_labs" | "/api/student_courses" | "/api/student_lab_context" | "/api/sync_lab_session" | "/api/sync_workspace" | "/api/update_course" | "/api/update_lab" | "/api/update_test_case" | "/api/user_settings" | "/instructor/create_user/api" | "/instructor/manage_roles/api" | "/instructor/user_search/api" | "/login/api" | "/logout/api" | "/verify"
type PageRoutes = never
type LayoutRoutes = "/" | "/instructor" | "/student"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/add_course_lab": {}
  "/api/add_course_member": {}
  "/api/course_labs": {}
  "/api/course_members": {}
  "/api/create_course": {}
  "/api/create_lab": {}
  "/api/create_test_case": {}
  "/api/delete_lab": {}
  "/api/delete_test_case": {}
  "/api/grade_lab": {}
  "/api/grade_status": {}
  "/api/lab_courses": {}
  "/api/lab_submissions": {}
  "/api/list_courses": {}
  "/api/list_labs": {}
  "/api/list_test_cases": {}
  "/api/load_lab_session": {}
  "/api/load_workspace": {}
  "/api/remove_course_lab": {}
  "/api/remove_course_member": {}
  "/api/run": {}
  "/api/score": {}
  "/api/student_course_labs": {}
  "/api/student_courses": {}
  "/api/student_lab_context": {}
  "/api/sync_lab_session": {}
  "/api/sync_workspace": {}
  "/api/update_course": {}
  "/api/update_lab": {}
  "/api/update_test_case": {}
  "/api/user_settings": {}
  "/docs": {}
  "/help": {}
  "/instructor": {}
  "/instructor/courses": {}
  "/instructor/courses/add_member": {}
  "/instructor/courses/create": {}
  "/instructor/courses/drop_member": {}
  "/instructor/courses/labs": {}
  "/instructor/courses/roster": {}
  "/instructor/create_user": {}
  "/instructor/create_user/api": {}
  "/instructor/edit_lab/[uid]": { "uid": string; }
  "/instructor/labs": {}
  "/instructor/manage_roles": {}
  "/instructor/manage_roles/api": {}
  "/instructor/user_search": {}
  "/instructor/user_search/api": {}
  "/labs": {}
  "/login": {}
  "/login/api": {}
  "/logout/api": {}
  "/new-project": {}
  "/profile": {}
  "/projects": {}
  "/projects/[projectId]": { "projectId": string; }
  "/settings": {}
  "/student": {}
  "/student/docs": {}
  "/student/help": {}
  "/student/labs": {}
  "/student/labs-root": {}
  "/student/labs/[uid]": { "uid": string; }
  "/student/new-project": {}
  "/student/profile": {}
  "/student/projects": {}
  "/student/projects/[projectId]": { "projectId": string; }
  "/student/settings": {}
  "/ta": {}
  "/verify": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/instructor": never
  "/student": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
