// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/courses/add_member/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor/courses/add_member">> = Specific
  const handler = {} as typeof import("../../app/instructor/courses/add_member/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/courses/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor/courses/create">> = Specific
  const handler = {} as typeof import("../../app/instructor/courses/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/courses/drop_member/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor/courses/drop_member">> = Specific
  const handler = {} as typeof import("../../app/instructor/courses/drop_member/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/courses/labs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor/courses/labs">> = Specific
  const handler = {} as typeof import("../../app/instructor/courses/labs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor/courses">> = Specific
  const handler = {} as typeof import("../../app/instructor/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/courses/roster/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor/courses/roster">> = Specific
  const handler = {} as typeof import("../../app/instructor/courses/roster/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/create_user/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor/create_user">> = Specific
  const handler = {} as typeof import("../../app/instructor/create_user/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/edit_lab/[uid]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor/edit_lab/[uid]">> = Specific
  const handler = {} as typeof import("../../app/instructor/edit_lab/[uid]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/labs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor/labs">> = Specific
  const handler = {} as typeof import("../../app/instructor/labs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/manage_roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor/manage_roles">> = Specific
  const handler = {} as typeof import("../../app/instructor/manage_roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor">> = Specific
  const handler = {} as typeof import("../../app/instructor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/user_search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instructor/user_search">> = Specific
  const handler = {} as typeof import("../../app/instructor/user_search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs">> = Specific
  const handler = {} as typeof import("../../app/labs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/new-project/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new-project">> = Specific
  const handler = {} as typeof import("../../app/new-project/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/docs">> = Specific
  const handler = {} as typeof import("../../app/student/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/help">> = Specific
  const handler = {} as typeof import("../../app/student/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/labs-root/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/labs-root">> = Specific
  const handler = {} as typeof import("../../app/student/labs-root/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/labs/[uid]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/labs/[uid]">> = Specific
  const handler = {} as typeof import("../../app/student/labs/[uid]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/labs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/labs">> = Specific
  const handler = {} as typeof import("../../app/student/labs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/new-project/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/new-project">> = Specific
  const handler = {} as typeof import("../../app/student/new-project/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student">> = Specific
  const handler = {} as typeof import("../../app/student/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/profile">> = Specific
  const handler = {} as typeof import("../../app/student/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/student/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/projects">> = Specific
  const handler = {} as typeof import("../../app/student/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/settings">> = Specific
  const handler = {} as typeof import("../../app/student/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ta">> = Specific
  const handler = {} as typeof import("../../app/ta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/add_course_lab/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/add_course_lab">> = Specific
  const handler = {} as typeof import("../../app/api/add_course_lab/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/add_course_member/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/add_course_member">> = Specific
  const handler = {} as typeof import("../../app/api/add_course_member/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/course_labs/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/course_labs">> = Specific
  const handler = {} as typeof import("../../app/api/course_labs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/course_members/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/course_members">> = Specific
  const handler = {} as typeof import("../../app/api/course_members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/create_course/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create_course">> = Specific
  const handler = {} as typeof import("../../app/api/create_course/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/create_lab/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create_lab">> = Specific
  const handler = {} as typeof import("../../app/api/create_lab/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/create_test_case/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create_test_case">> = Specific
  const handler = {} as typeof import("../../app/api/create_test_case/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/delete_lab/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/delete_lab">> = Specific
  const handler = {} as typeof import("../../app/api/delete_lab/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/delete_test_case/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/delete_test_case">> = Specific
  const handler = {} as typeof import("../../app/api/delete_test_case/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/grade_lab/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/grade_lab">> = Specific
  const handler = {} as typeof import("../../app/api/grade_lab/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/grade_status/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/grade_status">> = Specific
  const handler = {} as typeof import("../../app/api/grade_status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/lab_courses/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lab_courses">> = Specific
  const handler = {} as typeof import("../../app/api/lab_courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/lab_submissions/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lab_submissions">> = Specific
  const handler = {} as typeof import("../../app/api/lab_submissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/list_courses/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/list_courses">> = Specific
  const handler = {} as typeof import("../../app/api/list_courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/list_labs/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/list_labs">> = Specific
  const handler = {} as typeof import("../../app/api/list_labs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/list_test_cases/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/list_test_cases">> = Specific
  const handler = {} as typeof import("../../app/api/list_test_cases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/load_lab_session/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/load_lab_session">> = Specific
  const handler = {} as typeof import("../../app/api/load_lab_session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/load_workspace/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/load_workspace">> = Specific
  const handler = {} as typeof import("../../app/api/load_workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/remove_course_lab/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/remove_course_lab">> = Specific
  const handler = {} as typeof import("../../app/api/remove_course_lab/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/remove_course_member/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/remove_course_member">> = Specific
  const handler = {} as typeof import("../../app/api/remove_course_member/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/run">> = Specific
  const handler = {} as typeof import("../../app/api/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/score/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/score">> = Specific
  const handler = {} as typeof import("../../app/api/score/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/student_course_labs/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/student_course_labs">> = Specific
  const handler = {} as typeof import("../../app/api/student_course_labs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/student_courses/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/student_courses">> = Specific
  const handler = {} as typeof import("../../app/api/student_courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/student_lab_context/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/student_lab_context">> = Specific
  const handler = {} as typeof import("../../app/api/student_lab_context/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync_lab_session/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync_lab_session">> = Specific
  const handler = {} as typeof import("../../app/api/sync_lab_session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync_workspace/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync_workspace">> = Specific
  const handler = {} as typeof import("../../app/api/sync_workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/update_course/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/update_course">> = Specific
  const handler = {} as typeof import("../../app/api/update_course/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/update_lab/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/update_lab">> = Specific
  const handler = {} as typeof import("../../app/api/update_lab/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/update_test_case/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/update_test_case">> = Specific
  const handler = {} as typeof import("../../app/api/update_test_case/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user_settings/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user_settings">> = Specific
  const handler = {} as typeof import("../../app/api/user_settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/create_user/api/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/instructor/create_user/api">> = Specific
  const handler = {} as typeof import("../../app/instructor/create_user/api/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/manage_roles/api/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/instructor/manage_roles/api">> = Specific
  const handler = {} as typeof import("../../app/instructor/manage_roles/api/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/instructor/user_search/api/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/instructor/user_search/api">> = Specific
  const handler = {} as typeof import("../../app/instructor/user_search/api/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/api/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/login/api">> = Specific
  const handler = {} as typeof import("../../app/login/api/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/logout/api/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/logout/api">> = Specific
  const handler = {} as typeof import("../../app/logout/api/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verify/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/verify">> = Specific
  const handler = {} as typeof import("../../app/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/instructor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/instructor">> = Specific
  const handler = {} as typeof import("../../app/instructor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/student/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/student">> = Specific
  const handler = {} as typeof import("../../app/student/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
